# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Ensure Boost podspec points at the stable mirror + checksum (works with hoisted deps too).
boost_paths = [
  File.join(__dir__, '..', 'node_modules', 'react-native', 'third-party-podspecs', 'boost.podspec'),
  File.join(__dir__, '..', '..', 'node_modules', 'react-native', 'third-party-podspecs', 'boost.podspec'),
]
boost_url = 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
boost_sha = 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41'
boost_paths.each do |boost_podspec|
  next unless File.exist?(boost_podspec)
  contents = File.read(boost_podspec)
  updated = contents
    .sub(%r{https://.*boost_1_76_0\.tar\.bz2}, boost_url)
    .sub(/:sha256 => '[^']+'/, ":sha256 => '#{boost_sha}'")
  File.write(boost_podspec, updated) if updated != contents
end

platform :ios, '15.0'
use_modular_headers!
prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TaAnalyticsExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TaAnalyticsExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Ensure pods use a modern deployment target and avoid Folly clockid_t redefinitions on newer SDKs.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

        next unless target.name == 'RCT-Folly'

        %w[OTHER_CFLAGS OTHER_CPLUSPLUSFLAGS].each do |flag_key|
          flags = config.build_settings[flag_key]
          flags = ['$(inherited)'] if flags.nil?
          flags = flags.split(' ') if flags.is_a?(String)
          unless flags.include?('-DFOLLY_HAVE_CLOCK_GETTIME=1')
            flags << '-DFOLLY_HAVE_CLOCK_GETTIME=1'
          end
          config.build_settings[flag_key] = flags
        end
      end
    end
  end
end
